# ======================================
# TOPOLOGY and EXTERNAL DEPENDENCIES
# ======================================
application:
  name: email-activity
  topic:
    # Where domain request is consumed : ATTENTION please put between double quote to avoid ASCII check error
    domain-source: "email-source"
    # Where domain result is published
    domain-result: "email-result"

# ======================================
# Spring Boot
# ======================================
spring:
  application:
    name: ${application.name}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ======================================
# Management
# ======================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - info
info:
  app:
    name: ${application.name}
