# ======================================
# TOPOLOGY and EXTERNAL DEPENDENCIES
# ======================================
application:
  name: resilience-resilience4j

prefix:
  key1: value1

# ======================================
# Spring Boot
# ======================================
# https://resilience4j.readme.io/docs/getting-started-3
resilience4j.retry:
  instances:
    bridge:
      maxRetryAttempts: 3
      waitDuration: 250ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      resultPredicate: com.github.frtu.resilience.retry.RetryPredicate

spring:
  application:
    name: ${application.name}
  main:
    # SERVLET or REACTIVE
    web-application-type: REACTIVE

# ======================================
# Management
# ======================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - retry
          - retryevents
info:
  app:
    name: ${application.name}
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
