# ======================================
# TOPOLOGY and EXTERNAL DEPENDENCIES
# ======================================
application:
  name: resilience-rate-limiter

prefix:
  key1: value1

# https://resilience4j.readme.io/docs/ratelimiter
resilience4j.ratelimiter:
  instances:
    send:
      limitForPeriod: 2
      limitRefreshPeriod: 5s
      timeoutDuration: 1
      registerHealthIndicator: true

# ======================================
# Spring Boot
# ======================================
spring:
  application:
    name: ${application.name}

  redis:
    hostname: localhost
    port: 6379

# ======================================
# Management
# ======================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
info:
  app:
    name: ${application.name}
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
